// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatServerClient is the client API for ChatServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServerClient interface {
	GetConnectedClients(ctx context.Context, in *ConnectedClientsRequest, opts ...grpc.CallOption) (*ConnectedClientsResponse, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Message(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error)
	ReceiveMessages(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (ChatServer_ReceiveMessagesClient, error)
}

type chatServerClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServerClient(cc grpc.ClientConnInterface) ChatServerClient {
	return &chatServerClient{cc}
}

func (c *chatServerClient) GetConnectedClients(ctx context.Context, in *ConnectedClientsRequest, opts ...grpc.CallOption) (*ConnectedClientsResponse, error) {
	out := new(ConnectedClientsResponse)
	err := c.cc.Invoke(ctx, "/msg.ChatServer/GetConnectedClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServerClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/msg.ChatServer/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServerClient) Message(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/msg.ChatServer/Message", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServerClient) ReceiveMessages(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (ChatServer_ReceiveMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatServer_ServiceDesc.Streams[0], "/msg.ChatServer/ReceiveMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServerReceiveMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatServer_ReceiveMessagesClient interface {
	Recv() (*ChatMessage, error)
	grpc.ClientStream
}

type chatServerReceiveMessagesClient struct {
	grpc.ClientStream
}

func (x *chatServerReceiveMessagesClient) Recv() (*ChatMessage, error) {
	m := new(ChatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServerServer is the server API for ChatServer service.
// All implementations must embed UnimplementedChatServerServer
// for forward compatibility
type ChatServerServer interface {
	GetConnectedClients(context.Context, *ConnectedClientsRequest) (*ConnectedClientsResponse, error)
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Message(context.Context, *ChatMessage) (*MessageResponse, error)
	ReceiveMessages(*ReceiveRequest, ChatServer_ReceiveMessagesServer) error
	mustEmbedUnimplementedChatServerServer()
}

// UnimplementedChatServerServer must be embedded to have forward compatible implementations.
type UnimplementedChatServerServer struct {
}

func (UnimplementedChatServerServer) GetConnectedClients(context.Context, *ConnectedClientsRequest) (*ConnectedClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnectedClients not implemented")
}
func (UnimplementedChatServerServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedChatServerServer) Message(context.Context, *ChatMessage) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Message not implemented")
}
func (UnimplementedChatServerServer) ReceiveMessages(*ReceiveRequest, ChatServer_ReceiveMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveMessages not implemented")
}
func (UnimplementedChatServerServer) mustEmbedUnimplementedChatServerServer() {}

// UnsafeChatServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServerServer will
// result in compilation errors.
type UnsafeChatServerServer interface {
	mustEmbedUnimplementedChatServerServer()
}

func RegisterChatServerServer(s grpc.ServiceRegistrar, srv ChatServerServer) {
	s.RegisterService(&ChatServer_ServiceDesc, srv)
}

func _ChatServer_GetConnectedClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectedClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServerServer).GetConnectedClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ChatServer/GetConnectedClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServerServer).GetConnectedClients(ctx, req.(*ConnectedClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatServer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ChatServer/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServerServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatServer_Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServerServer).Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ChatServer/Message",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServerServer).Message(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatServer_ReceiveMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServerServer).ReceiveMessages(m, &chatServerReceiveMessagesServer{stream})
}

type ChatServer_ReceiveMessagesServer interface {
	Send(*ChatMessage) error
	grpc.ServerStream
}

type chatServerReceiveMessagesServer struct {
	grpc.ServerStream
}

func (x *chatServerReceiveMessagesServer) Send(m *ChatMessage) error {
	return x.ServerStream.SendMsg(m)
}

// ChatServer_ServiceDesc is the grpc.ServiceDesc for ChatServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.ChatServer",
	HandlerType: (*ChatServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConnectedClients",
			Handler:    _ChatServer_GetConnectedClients_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _ChatServer_Connect_Handler,
		},
		{
			MethodName: "Message",
			Handler:    _ChatServer_Message_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveMessages",
			Handler:       _ChatServer_ReceiveMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/message/proto/message.proto",
}
